  # configs/ablation_study.yaml
  wandb_project: "MSPI_Simple_seed_42"

  # Base template for all experiments
  template_config: &template
    learning_rate: 9e-3
    weight_decay: 5e-6
    use_curriculum_learning: true
    difficulty_method: "euclidean_distance"
    num_epochs: 30
    batch_size: 48
    train_dataset: "IEMO"
    evaluation_mode: "cross_corpus"

    class_weights:
      neutral: 1.0
      happy: 1.0
      sad: 1.0
      anger: 1.0

    curriculum_epochs: 15
    curriculum_pacing: "sqrt"
    use_difficulty_scaling: True
    use_speaker_disentanglement: True

    expected_vad:
      0: [3.0, 3.0, 3.0]  # neutral
      1: [4.2, 3.8, 3.5]  # happy
      2: [1.8, 2.2, 2.5]  # sad
      3: [2.5, 4.0, 3.2]  # anger

  experiments:
    - <<: *template
      name: "Scaling + Spkr"
      use_curriculum_learning: false


    - <<: *template
      name: "Curriculum+ Spkr"
      curriculum_pacing: "linear"
      use_curriculum_learning: true
    
    - <<: *template
      name: "Full System + Spkr"
      curriculum_pacing: "linear"
      use_curriculum_learning: true
      use_difficulty_scaling: false


    - <<: *template
      name: "Spkr Only"
      # curriculum_pacing: "sqrt"
      use_curriculum_learning: false
      use_difficulty_scaling: false
  

    - <<: *template
      name: "Baseline"
      # curriculum_pacing: "sqrt"
      use_curriculum_learning: false
      use_difficulty_scaling: false
      use_speaker_disentanglement: false


    - <<: *template
      name: "Curriculum Only"
      # curriculum_pacing: "sqrt"
      use_curriculum_learning: true
      use_difficulty_scaling: false
      use_speaker_disentanglement: false
