# Adversarial learning configuration
experiment_name: "adversarial_neutral_contrast"
wandb_project: "linear_pacing_comparison"

# Training settings
batch_size: 48
num_epochs: 20
learning_rate: 9e-3
weight_decay: 1e-5

# Model settings
hidden_dim: 1024
dropout: 0.3
num_classes: 4

# Dataset settings
train_dataset: "MSPI"  # MSPI, IEMO, or MSPP

# Evaluation settings - only cross-corpus for adversarial
val_split: 0.2

# Adversarial Learning settings
use_adversarial_learning: true
adversarial_alpha: 0.5  # Weight for adversarial component
difficulty_method: "euclidean_distance"

# Expected VAD values for difficulty calculation
expected_vad:
  0: [3.0, 3.0, 3.0]  # neutral
  1: [4.2, 3.8, 3.5]  # happy
  2: [1.8, 2.2, 2.5]  # sad
  3: [2.5, 4.0, 3.2]  # anger

# Class labels
class_names: ["neutral", "happy", "sad", "anger"]