_wandb:
    value:
        cli_version: 0.21.1
        e:
            t6hjukuptcdu9htx5z1g83lb68g0nups:
                args:
                    - --config
                    - ./configs/ablation.yaml
                    - --all
                codePath: Version B/main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "250375106560"
                        used: "218470801408"
                email: carol.wasef@torontomu.ca
                executable: /media/carol/Data/Documents/Emo_rec/Notebooks/emotion2vec_HAF/Version B/.venv/bin/python
                git:
                    commit: f5ceb0c84131ff2f59ac32ca86544e026676b499
                    remote: https://github.com/wasef-c/emotion2vec_HAF.git
                gpu: NVIDIA GeForce RTX 2080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2944
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2080
                      uuid: GPU-0772a441-05f3-a402-6e85-77d70b09b895
                host: carol-Legion-T730-28ICO
                memory:
                    total: "33587265536"
                os: Linux-6.5.0-28-generic-x86_64-with-glibc2.35
                program: /media/carol/Data/Documents/Emo_rec/Notebooks/emotion2vec_HAF/Version B/main.py
                python: CPython 3.10.12
                root: /media/carol/Data/Documents/Emo_rec/Notebooks/emotion2vec_HAF/Version B
                startedAt: "2025-08-10T18:35:54.931188Z"
                writerId: t6hjukuptcdu9htx5z1g83lb68g0nups
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 49
                - 51
                - 53
            "3":
                - 13
                - 16
                - 24
            "4": 3.10.12
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 48
class_names:
    value:
        - neutral
        - happy
        - sad
        - anger
curriculum_epochs:
    value: 10
curriculum_pacing:
    value: sqrt
difficulty_method:
    value: euclidean_distance
dropout:
    value: 0.3
evaluation_mode:
    value: cross_corpus
expected_vad:
    value:
        "0":
            - 3
            - 3
            - 3
        "1":
            - 4.2
            - 3.8
            - 3.5
        "2":
            - 1.8
            - 2.2
            - 2.5
        "3":
            - 2.5
            - 4
            - 3.2
experiment_name:
    value: Curr+Scaling
hidden_dim:
    value: 1024
learning_rate:
    value: 9e-05
num_classes:
    value: 4
num_epochs:
    value: 30
train_dataset:
    value: MSPI
use_curriculum_learning:
    value: true
val_split:
    value: 0.2
wandb_project:
    value: emotion2vec_simple
weight_decay:
    value: 5e-06
